# .github/workflows/email-test.yml

name: Email Test Workflow

on:
  push:
    branches:
      - main  # Trigger workflow only on push to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, world!"

      - name: <!--email_off-->22f2000488@ds.study.iitm.ac.in<!--/email_off-->
        run: echo "This is a test email label"
